/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package classes;

import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import java.awt.Image;
import java.awt.Graphics;
import javax.swing.ImageIcon;

/*   
============ALUNOS===========
Lucas Rodrigues – RA: 21069949
Danilo Ferrari – RA: 21086355
Lucas Oliveira – RA: 21094755
Manoel Merlin – RA: 21154353
=============================
*/

public class App extends javax.swing.JFrame {

    /**
     * Creates new form App
     */
    public App() {
        initComponents();
        this.setExtendedState(6);
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ImageIcon icon = new ImageIcon(getClass().getResource("/icons/bg.png"));
        Image image = icon.getImage();
        framePrincipal = new javax.swing.JDesktopPane(){

            public void paintComponent(Graphics g){
                g.drawImage(image,0,0,getWidth(),getHeight(),this);
            }

        };
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtContas = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        btnListarTodas = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuCadastrar = new javax.swing.JMenu();
        btnNormal = new javax.swing.JMenuItem();
        btnEspecial = new javax.swing.JMenuItem();
        menuRelatorios = new javax.swing.JMenu();
        btnListar = new javax.swing.JMenuItem();
        btnBuscar = new javax.swing.JMenuItem();
        menuMovimentar = new javax.swing.JMenu();
        btnDeposito = new javax.swing.JMenuItem();
        btnSaque = new javax.swing.JMenuItem();
        menuSair = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Banco UAM");

        jPanel1.setBackground(new java.awt.Color(233, 247, 241));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder("Contas"), "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N

        txtContas.setColumns(20);
        txtContas.setRows(5);
        jScrollPane1.setViewportView(txtContas);

        jLabel1.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jLabel1.setText("Todas as Contas");

        btnListarTodas.setText("Listar todas");
        btnListarTodas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarTodasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 341, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnListarTodas)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnListarTodas, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/logo.png"))); // NOI18N
        jLabel2.setText("jLabel2");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Por - Lucas Rodrigues, Danilo Ferrari, Lucas Oliveira e Manoel.");

        framePrincipal.setLayer(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        framePrincipal.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        framePrincipal.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout framePrincipalLayout = new javax.swing.GroupLayout(framePrincipal);
        framePrincipal.setLayout(framePrincipalLayout);
        framePrincipalLayout.setHorizontalGroup(
            framePrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(framePrincipalLayout.createSequentialGroup()
                .addGroup(framePrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(framePrincipalLayout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(framePrincipalLayout.createSequentialGroup()
                        .addGap(494, 494, 494)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(framePrincipalLayout.createSequentialGroup()
                        .addGap(405, 405, 405)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 683, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(1526, Short.MAX_VALUE))
        );
        framePrincipalLayout.setVerticalGroup(
            framePrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(framePrincipalLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(87, 87, 87)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(721, Short.MAX_VALUE))
        );

        jMenuBar1.setBackground(new java.awt.Color(102, 255, 204));
        jMenuBar1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        menuCadastrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/usericon.png"))); // NOI18N
        menuCadastrar.setText("Cadastrar Conta     ");
        menuCadastrar.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        btnNormal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/simple-money-bag.png"))); // NOI18N
        btnNormal.setText("Conta Normal");
        btnNormal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNormalActionPerformed(evt);
            }
        });
        menuCadastrar.add(btnNormal);

        btnEspecial.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/money-bag.png"))); // NOI18N
        btnEspecial.setText("Conta Especial");
        btnEspecial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEspecialActionPerformed(evt);
            }
        });
        menuCadastrar.add(btnEspecial);

        jMenuBar1.add(menuCadastrar);

        menuRelatorios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/news-report.png"))); // NOI18N
        menuRelatorios.setText("Relatórios     ");
        menuRelatorios.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        btnListar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/listartodos.png"))); // NOI18N
        btnListar.setText("Listar todas as contas");
        btnListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarActionPerformed(evt);
            }
        });
        menuRelatorios.add(btnListar);

        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/pesquisar.png"))); // NOI18N
        btnBuscar.setText("Buscar contas pelo número");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        menuRelatorios.add(btnBuscar);

        jMenuBar1.add(menuRelatorios);

        menuMovimentar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/transaction.png"))); // NOI18N
        menuMovimentar.setText("Movimentação     ");
        menuMovimentar.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        btnDeposito.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/money-deposit.png"))); // NOI18N
        btnDeposito.setText("Depósito");
        btnDeposito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDepositoActionPerformed(evt);
            }
        });
        menuMovimentar.add(btnDeposito);

        btnSaque.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/savings.png"))); // NOI18N
        btnSaque.setText("Saque");
        btnSaque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaqueActionPerformed(evt);
            }
        });
        menuMovimentar.add(btnSaque);

        jMenuBar1.add(menuMovimentar);

        menuSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/exit-to-app-button.png"))); // NOI18N
        menuSair.setText("Sair");
        menuSair.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        menuSair.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                menuSairItemStateChanged(evt);
            }
        });
        menuSair.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                menuSairMenuSelected(evt);
            }
        });
        menuSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuSairMouseClicked(evt);
            }
        });
        menuSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSairActionPerformed(evt);
            }
        });
        menuSair.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                menuSairPropertyChange(evt);
            }
        });
        jMenuBar1.add(menuSair);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(framePrincipal)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(framePrincipal)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    private void btnNormalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNormalActionPerformed
        frameCliente fCliente = new frameCliente();
        framePrincipal.add(fCliente);
        fCliente.setVisible(true);
        fCliente.setPosicao();
    }//GEN-LAST:event_btnNormalActionPerformed

    private void btnListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarActionPerformed
        GerenciaContas gc = new GerenciaContas();
        txtContas.setText(gc.listar());   
       
    }//GEN-LAST:event_btnListarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        frameListar fListar = new frameListar();
        framePrincipal.add(fListar);
        fListar.setVisible(true);
        fListar.setPosicao();
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnDepositoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDepositoActionPerformed
        frameDepositar fDeposito = new frameDepositar();
        framePrincipal.add(fDeposito);
        fDeposito.setVisible(true);
        fDeposito.setPosicao();
    }//GEN-LAST:event_btnDepositoActionPerformed

    private void btnEspecialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEspecialActionPerformed
        frameEspecial fEspecial = new frameEspecial();
        framePrincipal.add(fEspecial);
        fEspecial.setVisible(true);
        fEspecial.setPosicao();
    }//GEN-LAST:event_btnEspecialActionPerformed

    private void menuSairPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_menuSairPropertyChange
        //System.exit(0);
    }//GEN-LAST:event_menuSairPropertyChange

    private void menuSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_menuSairActionPerformed

    private void menuSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuSairMouseClicked
        System.exit(0);
    }//GEN-LAST:event_menuSairMouseClicked

    private void menuSairMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_menuSairMenuSelected
        //System.exit(0);
    }//GEN-LAST:event_menuSairMenuSelected

    private void menuSairItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_menuSairItemStateChanged

    }//GEN-LAST:event_menuSairItemStateChanged

    private void btnSaqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaqueActionPerformed
        frameSacar fSacar = new frameSacar();
        framePrincipal.add(fSacar);
        fSacar.setVisible(true);
        fSacar.setPosicao();
    }//GEN-LAST:event_btnSaqueActionPerformed

    private void btnListarTodasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarTodasActionPerformed
        GerenciaContas gc = new GerenciaContas();
        txtContas.setText(gc.listar());
    }//GEN-LAST:event_btnListarTodasActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new App().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem btnBuscar;
    private javax.swing.JMenuItem btnDeposito;
    private javax.swing.JMenuItem btnEspecial;
    private javax.swing.JMenuItem btnListar;
    private javax.swing.JButton btnListarTodas;
    private javax.swing.JMenuItem btnNormal;
    private javax.swing.JMenuItem btnSaque;
    private javax.swing.JDesktopPane framePrincipal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenu menuCadastrar;
    private javax.swing.JMenu menuMovimentar;
    private javax.swing.JMenu menuRelatorios;
    private javax.swing.JMenu menuSair;
    private javax.swing.JTextArea txtContas;
    // End of variables declaration//GEN-END:variables
}
